### PR TITLE
Fix temp/backup identifier in table materialization

### LINKED ISSUE #185: Temp/backup relations do not use model alias for table materialization
### Expected behavior

We override the `generate_alias_name` macro in our project to generate different table names for dev vs prod. We would expect the temp table name to look like `alias_name__dbt_tmp`. 

### Actual behavior

The final identifier gets written out correctly, but we notice that the temp and backup tables do not use the alias, but instead look like `model_name__dbt_tmp`. 

I believe the issue is that lines 3-4 in the [table materialization macro](https://github.com/dbt-labs/dbt-presto/blob/0.20.latest/dbt/include/presto/macros/materializations/table.sql) use `model['name']` rather than `model['alias']`. I'd be happy to submit a change for this if that is all that is needed

### Steps To Reproduce

For example, with a model called "model1" configured like:

```
{{ config(alias="my_new_name", materialization=table) }}
```

The temp CTAS would look like:
```
create table "catalog"."schema"."model1__dbt_tmp"
...

```

where we would expect the identifier to be `my_new_name__dbt_tmp`. This does not happen for incremental materializations, only table.

### Log output/Screenshots

_No response_

### Operating System

MacOS

### dbt version

0.20.0 (technically we're on dbt-presto, but looking to upgrade to dbt-trino soon)

### Trino Server version

386

### Python version

3.8.8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by damian3031**
## Overview
resolves #185 
Fix temp/backup identifier in table materialization

### CODE REVIEW

File: dbt/include/trino/macros/materializations/table.sql [hunk 1]
```diff
@@ -6,8 +6,8 @@
       {%- set on_table_exists = 'rename' -%}
   {% endif %}
   {%- set identifier = model['alias'] -%}
-  {%- set tmp_identifier = model['name'] + '__dbt_tmp' -%}
-  {%- set backup_identifier = model['name'] + '__dbt_backup' -%}
+  {%- set tmp_identifier = identifier ~ '__dbt_tmp' -%}
```
Comment (mdesmet) [inline dbt/include/trino/macros/materializations/table.sql:9]: Can we create the target relation first and leverage dbt's implementation instead of fiddling with alias ourselves?

**Review by mdesmet — APPROVED** [review]
Good work! Please squash the commits.

File: dbt/include/trino/macros/materializations/table.sql (hunk 1 above)
Comment (damian3031) [reply dbt/include/trino/macros/materializations/table.sql]: refactored

**Review by hovaesco — APPROVED** [review]
